module.exports = [
  { name: "Elves",
    cards: [
      { name: "Enchantress",
        type: "Minion",
        powerLevels: [5],
      },
      { name: "Bladesmith",
        type: "Minion",
        count: 2,
        powerLevels: [4],
      },
      { name: "Archer",
        type: "Minion",
        count: 3,
        powerLevels: [3, 4],
      },
      { name: "Treehugger",
        type: "Minion",
        count: 4,
        powerLevels: [2, 3],
      },
    ],
  },
];
